//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atraccion
    {
        public short idAtraccion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidadPersonas { get; set; }
        public string inglumentaria { get; set; }
        public string requisitos { get; set; }
        public Nullable<decimal> precioTotalAtraccion { get; set; }
        public Nullable<short> idGallery { get; set; }
    }
}
