//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destino
    {
        public short idDestino { get; set; }
        public string tipoDestino { get; set; }
        public string descripcion { get; set; }
        public Nullable<short> idTablaActividades { get; set; }
        public Nullable<short> idTablaAtracciones { get; set; }
        public string coordenadas { get; set; }
    }
}
