//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public short idGallery { get; set; }
        public string descripcion { get; set; }
        public byte[] image1 { get; set; }
        public byte[] image2 { get; set; }
        public byte[] image3 { get; set; }
        public byte[] image4 { get; set; }
        public byte[] image5 { get; set; }
        public byte[] image6 { get; set; }
        public byte[] image7 { get; set; }
        public byte[] image8 { get; set; }
        public byte[] image9 { get; set; }
    }
}
