//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class in04
    {
        public short id { get; set; }
        public string CodigoProducto { get; set; }
        public Nullable<int> Precio { get; set; }
        public string SaldoInventario { get; set; }
        public string FechaIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public Nullable<int> IDFamilia { get; set; }
        public string Descripcion { get; set; }
    }
}
