//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referencia
    {
        public short idReferencia { get; set; }
        public Nullable<short> idCliente { get; set; }
        public string descipcion { get; set; }
        public Nullable<short> calificacion { get; set; }
    }
}
