//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaColaboradores
    {
        public short idTablaColaboradores { get; set; }
        public string descripcion { get; set; }
        public string colaborador1 { get; set; }
        public string colaborador2 { get; set; }
        public string colaborador3 { get; set; }
        public string colaborador4 { get; set; }
        public string colaborador5 { get; set; }
    }
}
