//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaActividades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TablaActividades()
        {
            this.Servicio = new HashSet<Servicio>();
        }
    
        public short idTablaActividades { get; set; }
        public string descripcion { get; set; }
        public Nullable<short> actividad1 { get; set; }
        public Nullable<short> actividad2 { get; set; }
        public Nullable<short> actividad3 { get; set; }
        public Nullable<short> actividad4 { get; set; }
        public Nullable<short> actividad5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
