//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaToures
    {
        public short idTablaToures { get; set; }
        public string descripcion { get; set; }
        public Nullable<short> idTour1 { get; set; }
        public Nullable<short> idTour2 { get; set; }
        public Nullable<short> idTour3 { get; set; }
        public Nullable<short> idTour4 { get; set; }
        public Nullable<short> idTour5 { get; set; }
    }
}
