//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Servicio = new HashSet<Servicio>();
        }
    
        public short idTour { get; set; }
        public Nullable<short> idTabladestinos { get; set; }
        public string descripcion { get; set; }
        public string lugarSalida { get; set; }
        public string fechaCheckIn { get; set; }
        public string fechaCheckOut { get; set; }
        public string alimentacion { get; set; }
        public string horaSalida { get; set; }
        public string horaRegreso { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<short> idGallery { get; set; }
        public byte[] photo { get; set; }
        public string nombreTour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
