//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte
    {
        public short idTransporte { get; set; }
        public string tipo { get; set; }
        public string placa { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> capacidad { get; set; }
        public string color { get; set; }
        public Nullable<short> colaboradorChofer { get; set; }
        public Nullable<short> colaboradorResponsable { get; set; }
        public byte[] foto { get; set; }
    }
}
